### ISSUE TITLE
Are there any tutorial or example on how to use this?

### ISSUE THREAD

**Issue by MarisaKirisame** [Zimmi48/transfer#1]
I'd read the paper, but it is more focus on the abstract concept than concrete interface...

**Comment by Zimmi48** [comment]
Hi,
You are right about the paper, that's not the place to find concrete use cases and advice on how to use.
For now, there isn't any tutorial but the [README](https://github.com/Zimmi48/transfer/blob/master/library/README.md) is a good place to start and there are basic examples in [NArithTransfer.v](https://github.com/Zimmi48/transfer/blob/master/library/NArithTransfer.v) and [NArithTests.v](https://github.com/Zimmi48/transfer/blob/master/library/NArithTests.v).
I'm planning to add more interesting examples, inspired by [Raggi et al](http://arxiv.org/abs/1505.02449) (but they do it in Isabelle with the Transfer package).
To make a tutorial, I would need more work cases. If you have one in mind, I'd be glad to help you with it as it may help me understand what needs to be said in such a tutorial.

**Comment by MarisaKirisame** [comment]
Thankyou,  I will go have a read.
If I have  any work case, I will be happy to tell you :)
